### ISSUE TITLE
Actualizar Rankings

### ISSUE THREAD

**Issue by AntonioPMCS** [ETIST/wordpress-page#1]
Após o 2º torneio etist (18 de Março de 2017), é preciso:

- Determinar a tabela de classificações
- Fazer a atribuição de pontos
- Somar os pontos aos atletas e introduzir os novos atletas no ranking, reeordenando-o.

**Comment by AntonioPMCS** [comment]
Concluído, rankings actualizados

**Comment by FMCalisto** [comment]
Estás todo Scrum Master!
