### ISSUE TITLE
Criar página de apresentação

### ISSUE THREAD

**Issue by AntonioPMCS** [ETIST/wordpress-page#5]
À data de abertura desta issue, o conteúdo da homepage eram os posts mais recentes.

Deverá ser criada uma página de apresentação, com um bom texto explicando quem somos, o que oferecemos e porque existimos no técnico.

**Comment by FMCalisto** [comment]
Eu diria que neste sentido a página principal deveria ter as seguintes informações:

1) Um slider com "stories";

2) Colocar feature content (podem ser featured athlete);

3) Um plugin que mostra coisas partilhadas nas redes sociais;

4) Zona de anúncios;

5) Patrocinios;

Algumas ideias:

http://athletics.uchicago.edu/landing/index

http://www.recreation.ubc.ca/sport-clubs/tennis/

http://www.tennis-warehouse.com/team/

**Comment by AntonioPMCS** [comment]
Parece-me um óptimo plano! Siga pa frente

**Comment by FMCalisto** [comment]
Sim. Daí ter-me metido como assignee. O meu único problema é que só devo ter tempo para pegar nisto em Dezembro.

**Comment by AntonioPMCS** [comment]
Então fazemos assim, provisoriamente eu faço uma coisa mais simples. Quando tiveres tempo pegas naquilo.

Em geral o design do site não está lá grande coisa. Não é a minha área mais forte e colocar o resto do conteúdo já tem dado imenso trabalho...

**Comment by FMCalisto** [comment]
Concordo e é o meu forte. Por isso faz o minimo que eu depois faço o resto. Já estás a ter imenso trabalho com isto e estás a pegar nisto sozinho.

Obrigado!

**Comment by AntonioPMCS** [comment]
Versão provisória criada. Conteúdo:

- Slider com eventos do momento implementados como posts na categoria "Notícias". A imagem que aparece no slider é a "featured image" do post.

- Link para o FAQ.
